// compile_and_run_and_check_exit_status 5

func f(int a, bool b) -> int { return a; }
func main() -> int {
    return f(a = 5, b = false);
}
